//
// Created by Guilherme Camacho on 30/10/2023.
//

#ifndef POO_SIMULADOR_HABITACAO_REFRIGERADOR_H
#define POO_SIMULADOR_HABITACAO_REFRIGERADOR_H


class Refrigerador {

};


#endif //POO_SIMULADOR_HABITACAO_REFRIGERADOR_H
